/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Program;

import static Program.DbAdmin.chartMingguan;
import static Program.DbAdmin.jTextField8;
import static Program.DbAdmin.jTextField9;
import com.mysql.jdbc.Connection;
import java.awt.Color;
import java.awt.HeadlessException;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.CategoryPlot;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.chart.renderer.category.BarRenderer;
import org.jfree.data.jdbc.JDBCCategoryDataset;

/**
 *
 * @author Daffa Afifi Syahrony
 */
public class LogIn extends javax.swing.JFrame {

    /**
     * Creates new form LogIn
     */
    public LogIn() {
        initComponents();
        setTitle("Retnosari App");
        
        txtUsername.setVisible(false);
        txtPassword.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bodyPanel = new javax.swing.JPanel();
        SignInPanel = new javax.swing.JPanel();
        btnLogin = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        txtPassword = new javax.swing.JPasswordField();
        lblUsername = new javax.swing.JLabel();
        lblPassword = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        bodyPanel.setLayout(new java.awt.CardLayout());

        SignInPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLoginMouseClicked(evt);
            }
        });
        SignInPanel.add(btnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 450, 140, 40));

        txtUsername.setBackground(new java.awt.Color(44, 107, 52));
        txtUsername.setFont(new java.awt.Font("Verdana", 0, 22)); // NOI18N
        txtUsername.setForeground(new java.awt.Color(255, 255, 255));
        txtUsername.setBorder(null);
        txtUsername.setCaretColor(new java.awt.Color(255, 255, 255));
        txtUsername.setMargin(new java.awt.Insets(2, 10, 2, 2));
        txtUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsernameActionPerformed(evt);
            }
        });
        SignInPanel.add(txtUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 310, 330, 30));

        txtPassword.setBackground(new java.awt.Color(44, 107, 52));
        txtPassword.setFont(new java.awt.Font("Times New Roman", 1, 22)); // NOI18N
        txtPassword.setForeground(new java.awt.Color(255, 255, 255));
        txtPassword.setBorder(null);
        txtPassword.setCaretColor(new java.awt.Color(255, 255, 255));
        txtPassword.setMargin(new java.awt.Insets(2, 4, 2, 2));
        SignInPanel.add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 370, 330, 30));

        lblUsername.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        lblUsername.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblUsernameMouseClicked(evt);
            }
        });
        SignInPanel.add(lblUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 300, 330, 40));

        lblPassword.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        lblPassword.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblPasswordMouseClicked(evt);
            }
        });
        SignInPanel.add(lblPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 360, 330, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Sign In.png"))); // NOI18N
        SignInPanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        bodyPanel.add(SignInPanel, "card2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bodyPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bodyPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsernameActionPerformed

    private void lblUsernameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblUsernameMouseClicked
        // TODO add your handling code here:
        lblUsername.setVisible(false);
        txtUsername.setVisible(true);
    }//GEN-LAST:event_lblUsernameMouseClicked

    private void lblPasswordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblPasswordMouseClicked
        // TODO add your handling code here:
        lblPassword.setVisible(false);
        txtPassword.setVisible(true);
    }//GEN-LAST:event_lblPasswordMouseClicked

    private void btnLoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLoginMouseClicked
        // TODO add your handling code here:
        try {
            String sql="SELECT * FROM karyawan WHERE id_karyawan='"+txtUsername.getText()
                    +"'AND password='"+txtPassword.getText()+"'";
            java.sql.Connection conn=(java.sql.Connection)koneksi.getKoneksi();
            java.sql.PreparedStatement pst=conn.prepareStatement(sql);
            java.sql.ResultSet rs=pst.executeQuery(sql);
            if (rs.next()){
                String role = rs.getString("role");
                if (txtUsername.getText().equals(rs.getString("id_karyawan"))
                        && txtPassword.getText().equals(rs.getString("password"))){
                    if(role.equals("Staff")){
                        this.setVisible(false);
                        new DashboardStaff().setVisible(true);
                        DashboardStaff.namaTop6.setText(rs.getString("nama_karyawan"));
                        DashboardStaff.namaTop7.setText(rs.getString("nama_karyawan"));
                        DashboardStaff.namaTop8.setText(rs.getString("nama_karyawan"));
                        DashboardStaff.namaTop9.setText(rs.getString("nama_karyawan"));
                        DashboardStaff.namaTop10.setText(rs.getString("nama_karyawan"));
                        DashboardStaff.txtIdkarBB.setText(rs.getString("id_karyawan"));
                        DashboardStaff.txtIdkarbs.setText(rs.getString("id_karyawan"));
                        DashboardStaff.txtIdkarpesan.setText(rs.getString("id_karyawan"));
                        DashboardStaff.txtIdkarTrx.setText(rs.getString("id_karyawan"));
                        DashboardStaff.txtKodebarPesan2.setText(rs.getString("id_karyawan"));
                        JOptionPane.showMessageDialog(null, "Berhasil Login Sebagai Staff");
                    }
                    if(role.equals("Admin")){
                        this.setVisible(false);
                        new DbAdmin().setVisible(true);
                        DbAdmin.namaTop.setText(rs.getString("nama_karyawan"));
                        DbAdmin.namaTop1.setText(rs.getString("nama_karyawan"));
                        DbAdmin.namaTop2.setText(rs.getString("nama_karyawan"));
                        DbAdmin.namaTop3.setText(rs.getString("nama_karyawan"));
                        DbAdmin.namaTop4.setText(rs.getString("nama_karyawan"));
                        DbAdmin.namaTop5.setText(rs.getString("nama_karyawan"));
                        DbAdmin.namaTop6.setText(rs.getString("nama_karyawan"));
                        DbAdmin.namaTop7.setText(rs.getString("nama_karyawan"));
                        DbAdmin.txtIdkarBB.setText(rs.getString("id_karyawan"));
                        DbAdmin.txtIdkarbs.setText(rs.getString("id_karyawan"));
                        DbAdmin.txtIdkarpesan.setText(rs.getString("id_karyawan"));
                        DbAdmin.txtIdkarTrx.setText(rs.getString("id_karyawan"));
                        DbAdmin.txtKodebarPesan2.setText(rs.getString("id_karyawan"));
                        JOptionPane.showMessageDialog(null, "Berhasil Login Sebagai Admin");
                    } 
                    }else{
                    JOptionPane.showMessageDialog(null, "ID Karyawan atau Password Salah");
                    }
            }else{
                JOptionPane.showMessageDialog(null, "ID Karyawan atau Password Salah");
            }
        } catch (HeadlessException | SQLException e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }

    }//GEN-LAST:event_btnLoginMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LogIn().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel SignInPanel;
    private javax.swing.JPanel bodyPanel;
    private javax.swing.JLabel btnLogin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
