/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Program;

import static Program.DbAdmin.jComboBox1;
import static Program.DbAdmin.jTable10;
import static Program.DbAdmin.jTable4;
import java.awt.Image;
import java.awt.event.MouseEvent;
import java.io.File;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author DELL
 */
public class Mastermotif extends javax.swing.JFrame {
private DefaultTableModel modelmotif;
    /**
     * Creates new form Mastermotif
     */
    public Mastermotif() {
        initComponents();
   //     jTable1.setAutoResizeMode(javax.swing.JTable.AUTO);
        Tabelmastermotif.setGridColor(new java.awt.Color(197, 210, 197));
        Tabelmastermotif.setRowHeight(25);
        Tabelmastermotif.setSelectionBackground(new java.awt.Color(244, 171, 78));
        Tabelmastermotif.setSelectionForeground(new java.awt.Color(0, 0, 0));
        
        
        
        modelmotif = new DefaultTableModel();
        Tabelmastermotif.setModel(modelmotif);
        modelmotif.addColumn("NO");
        modelmotif.addColumn("ID MOTIF");
        modelmotif.addColumn("NAMA MOTIF");
        
        getDatamotif();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        Update = new javax.swing.JMenuItem();
        Hapus = new javax.swing.JMenuItem();
        PanelMasterBatik = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Previewimage = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        Txt_Gambar = new javax.swing.JTextField();

        Update.setText("Update");
        Update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateActionPerformed(evt);
            }
        });
        jPopupMenu1.add(Update);

        Hapus.setText("Hapus");
        Hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HapusActionPerformed(evt);
            }
        });
        jPopupMenu1.add(Hapus);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PanelMasterBatik.setBackground(new java.awt.Color(255, 255, 255));
        PanelMasterBatik.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        PanelMasterBatik.setPreferredSize(new java.awt.Dimension(730, 530));
        PanelMasterBatik.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Tabelmastermotif.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        Tabelmastermotif.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        Tabelmastermotif.setGridColor(new java.awt.Color(197, 210, 197));
        Tabelmastermotif.setSelectionBackground(new java.awt.Color(244, 171, 78));
        Tabelmastermotif.setSelectionForeground(new java.awt.Color(0, 0, 0));
        Tabelmastermotif.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TabelmastermotifMouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                TabelmastermotifMouseReleased(evt);
            }
        });
        jScrollPane1.setViewportView(Tabelmastermotif);

        PanelMasterBatik.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 80, 300, 350));

        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        PanelMasterBatik.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 0, 40, 40));

        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        PanelMasterBatik.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 460, 110, 40));

        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        PanelMasterBatik.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 4, 30, 30));
        PanelMasterBatik.add(Previewimage, new org.netbeans.lib.awtextra.AbsoluteConstraints(422, 80, 170, 170));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/GambarBAtikkk.png"))); // NOI18N
        PanelMasterBatik.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(412, 130, 190, 60));

        Txt_NamaMotif.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        Txt_NamaMotif.setBorder(null);
        PanelMasterBatik.add(Txt_NamaMotif, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 320, 180, 30));

        jLabel43.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Mastermotifff1.png"))); // NOI18N
        PanelMasterBatik.add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 660, -1));

        Txt_Gambar.setForeground(new java.awt.Color(255, 255, 255));
        Txt_Gambar.setBorder(null);
        Txt_Gambar.setOpaque(false);
        PanelMasterBatik.add(Txt_Gambar, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 360, 180, -1));

        getContentPane().add(PanelMasterBatik, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 770, 550));

        setSize(new java.awt.Dimension(659, 546));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    
    
    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        this.setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        new PopUpMotif().setVisible(true);
        this.setVisible(false);
        this.setEnabled(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel4MouseClicked

    private void TabelmastermotifMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TabelmastermotifMouseReleased
        // TODO add your handling code here:
        if (evt.getButton()==MouseEvent.BUTTON3){
            if(evt.isPopupTrigger()&& Tabelmastermotif.getSelectedRowCount()!=0){
                jPopupMenu1.show(evt.getComponent(),evt.getX(),evt.getY());
            }
        }
    }//GEN-LAST:event_TabelmastermotifMouseReleased

    private void UpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateActionPerformed
    new PopUpMotif1().setVisible(true);
    
        
    }//GEN-LAST:event_UpdateActionPerformed

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        this.setVisible(false);
        try {
        java.sql.Connection cn = (Connection)koneksi.getKoneksi();
            Statement stt= cn.createStatement();
        String sql = "SELECT Motif FROM motifbatik ORDER BY Motif ASC";
        ResultSet res = stt.executeQuery(sql);
        while(res.next()){
            Object[] ob = new Object[4];
            ob[0] = res.getString(1);
            jComboBox1.addItem((String) ob[0]);
            DbAdmin.jcomboboxmotif.addItem((String) ob[0]);
            }
            res.close(); stt.close();
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_jLabel2MouseClicked

    private void TabelmastermotifMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TabelmastermotifMouseClicked
     int baris;
    baris = Tabelmastermotif.rowAtPoint(evt.getPoint());
        try{
        java.sql.Connection conn=(com.mysql.jdbc.Connection)koneksi.getKoneksi();
        String sql = "SELECT Motif,gambar FROM motifbatik WHERE id_motif =   '"+Tabelmastermotif.getValueAt(baris, 1).toString()+"'";
        java.sql.PreparedStatement pst = conn.prepareStatement(sql);
        ResultSet res = pst.executeQuery(sql);
           while(res.next()){
               Txt_NamaMotif.setText(res.getString(1));
               Txt_Gambar.setText(res.getString(2));
           }
        } catch(SQLException err){
             JOptionPane.showMessageDialog(null, err.getMessage() );
        }
        
        String newpath = "Uploads/ProfilImages";
        File directory = new File(newpath);
        {if(!directory.exists()){
        }
        ImageIcon imageiconn= new ImageIcon(newpath+"/"+Txt_Gambar.getText());
        Image image = imageiconn.getImage().getScaledInstance(270, 250, Image.SCALE_DEFAULT);
        ImageIcon imageIcon=new ImageIcon(image);
        Previewimage.setIcon(imageIcon); 
        }
    }//GEN-LAST:event_TabelmastermotifMouseClicked

    private void HapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HapusActionPerformed
        int barisSup = Tabelmastermotif.getSelectedRow();
        String idPemesanan = Tabelmastermotif.getValueAt(barisSup, 1).toString();
        try {
            String sql= "DELETE FROM motifbatik WHERE id_motif = '"+idPemesanan+"'";
            java.sql.Connection conn=(com.mysql.jdbc.Connection)koneksi.getKoneksi();
            java.sql.PreparedStatement pst = conn.prepareStatement(sql);
            pst.execute();
            JOptionPane.showMessageDialog(null, "Data Berhasil Dihapus");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Data Tidak Bisa Dihapus");
        }
        getDatamotif();
    }//GEN-LAST:event_HapusActionPerformed

    public void getDatamotif(){
        int a = 1;
        modelmotif.getDataVector().removeAllElements();
        modelmotif.getDataVector().removeAllElements();
        try {
        java.sql.Connection conn=(com.mysql.jdbc.Connection)koneksi.getKoneksi();
        String sql = "SELECT * FROM motifbatik";
        java.sql.PreparedStatement pst = conn.prepareStatement(sql);
        ResultSet res = pst.executeQuery(sql);
         while(res.next()){
               Object[] obj = new Object[3];
               obj[0] = a++;
               obj[1] = res.getString(1);
               obj[2] = res.getString(2);
               
             
               modelmotif.addRow(obj);
         }
        } catch (Exception e) {
        }
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Mastermotif.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Mastermotif.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Mastermotif.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Mastermotif.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Mastermotif().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Hapus;
    private javax.swing.JPanel PanelMasterBatik;
    private javax.swing.JLabel Previewimage;
    public static final javax.swing.JTable Tabelmastermotif = new javax.swing.JTable();
    private javax.swing.JTextField Txt_Gambar;
    public static final javax.swing.JTextField Txt_NamaMotif = new javax.swing.JTextField();
    private javax.swing.JMenuItem Update;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
