/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Program;

import java.awt.Component;
import java.awt.Image;
import java.awt.Toolkit;
import java.io.File;
import java.nio.file.Files;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import static Program.Mastermotif.Tabelmastermotif;
import javax.swing.JFrame;

/**
 *
 * @author DELL
 */
public class PopUpMotif1 extends javax.swing.JFrame {
private DefaultTableModel modelmotif;

    static void show(Component component, int x, int y) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * Creates new form PopUpMotif
     */
    public PopUpMotif1() {
        initComponents();
       
        Tabelmastermotif.setGridColor(new java.awt.Color(197, 210, 197));
        Tabelmastermotif.setRowHeight(25);
        Tabelmastermotif.setSelectionBackground(new java.awt.Color(244, 171, 78));
        Tabelmastermotif.setSelectionForeground(new java.awt.Color(0, 0, 0));
        
        
        
        modelmotif = new DefaultTableModel();
        Tabelmastermotif.setModel(modelmotif);
        modelmotif.addColumn("NO");
        modelmotif.addColumn("ID MOTIF");
        modelmotif.addColumn("NAMA MOTIF");
        getdata();
    }

    

    private void getdata(){
        
        try {
            String sql= "SELECT id_motif, Motif, gambar FROM motifbatik WHERE Motif  = '"+Mastermotif.Txt_NamaMotif.getText()+"'";
            java.sql.Connection conn=(com.mysql.jdbc.Connection)koneksi.getKoneksi();
            java.sql.Statement pst = conn.createStatement();
            java.sql.ResultSet res = pst.executeQuery(sql);
            while (res.next()) {                
                PopUpMotif1.Txt_IdMotif.setText(res.getString(1));
                PopUpMotif1.Txt_Motif.setText(res.getString(2));
                PopUpMotif1.Txt_Gambar.setText(res.getString(3));
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
        
        String newpath = "Uploads/ProfilImages";
        File directory = new File(newpath);
        {if(!directory.exists()){
        }
        ImageIcon imageiconn= new ImageIcon(newpath+"/"+Txt_Gambar.getText());
        Image image = imageiconn.getImage().getScaledInstance(270, 250, Image.SCALE_DEFAULT);
        ImageIcon imageIcon=new ImageIcon(image);
        Previewimage2.setIcon(imageIcon);
        }
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        Previewimage2 = new javax.swing.JLabel();
        Btn_Simpan = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 0, 40, 40));
        jPanel1.add(Previewimage2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 60, 180, 180));

        Btn_Simpan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Btn_SimpanMouseClicked(evt);
            }
        });
        jPanel1.add(Btn_Simpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 480, 90, 30));

        Txt_Motif.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        Txt_Motif.setBorder(null);
        jPanel1.add(Txt_Motif, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 434, 210, 30));

        Txt_IdMotif.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        Txt_IdMotif.setBorder(null);
        jPanel1.add(Txt_IdMotif, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 360, 210, 30));
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 265, 40, 40));

        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 265, 40, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Mastermotifff2.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 370, 550));

        Txt_Gambar.setEditable(false);
        Txt_Gambar.setOpaque(false);
        jPanel1.add(Txt_Gambar, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 320, 200, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        setSize(new java.awt.Dimension(363, 541));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        this.setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel2MouseClicked

    
    
    
    
    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
            try {
            JFileChooser chooser= new JFileChooser();
            chooser.showOpenDialog(null);
            File f=chooser.getSelectedFile();
            Toolkit toolkit=Toolkit.getDefaultToolkit();
            Image image=toolkit.getImage(chooser.getSelectedFile().getAbsolutePath());
            Image imagedResized=image.getScaledInstance(180, 180, Image.SCALE_DEFAULT);
            ImageIcon imageIcon=new ImageIcon(imagedResized);
            Previewimage2.setIcon(imageIcon);
            String filename = f.getAbsolutePath();
            filename=f.toString();
            Txt_Gambar.setText(f.getName());
            String newPath = "Uploads/ProfilImages";
            File directory = new File(newPath);
            if(!directory.exists()){
                directory.mkdirs();
            }
            File sourceFile = null;
            File DestinationFile = null;
            String Extension = filename.substring(filename.lastIndexOf('.')+1);
            sourceFile= new  File(filename);
            DestinationFile = new File(newPath+"/"+f.getName());
            Files.copy(sourceFile.toPath(), DestinationFile.toPath());
        } catch (Exception e) {
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel3MouseClicked

    private void Btn_SimpanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Btn_SimpanMouseClicked
        try {
            String sql ="UPDATE `motifbatik` SET `Motif`='"+Txt_Motif.getText()+"',`gambar`='"+Txt_Gambar.getText()+"' "
                    + "WHERE id_motif ="
                + "'"+Txt_IdMotif.getText()+"'";
        java.sql.Connection conn= (com.mysql.jdbc.Connection)koneksi.getKoneksi();
        java.sql.PreparedStatement pst = conn.prepareStatement(sql);
        pst.execute();
            JOptionPane.showMessageDialog(this, "Berhasil diupdate");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Gagal diupdate");
        }
        
        new Mastermotif().setVisible(true);
        this.setVisible(false);
        this.setEnabled(false);
    }//GEN-LAST:event_Btn_SimpanMouseClicked

    
    public void getDatamotif(){
        int a = 1;
        modelmotif.getDataVector().removeAllElements();
        modelmotif.getDataVector().removeAllElements();
        try {
        java.sql.Connection conn=(com.mysql.jdbc.Connection)koneksi.getKoneksi();
        String sql = "SELECT * FROM motifbatik";
        java.sql.PreparedStatement pst = conn.prepareStatement(sql);
        ResultSet res = pst.executeQuery(sql);
         while(res.next()){
               Object[] obj = new Object[3];
               obj[0] = a++;
               obj[1] = res.getString(1);
               obj[2] = res.getString(2);
               
             
               modelmotif.addRow(obj);
         }
        } catch (Exception e) {
        }
    }
    
    
    /**
     * 
     * 
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PopUpMotif1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PopUpMotif1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PopUpMotif1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PopUpMotif1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PopUpMotif1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Btn_Simpan;
    private javax.swing.JLabel Previewimage2;
    public static final javax.swing.JTextField Txt_Gambar = new javax.swing.JTextField();
    public static final javax.swing.JTextField Txt_IdMotif = new javax.swing.JTextField();
    public static final javax.swing.JTextField Txt_Motif = new javax.swing.JTextField();
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
